name: CICD

on:
  push:
    branches:
      - "main"

jobs:
  preparation:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, this is test pipeline"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Prod server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /var/www/html
    
    needs: [preparation] 
