name: CICD

on:
  push:
    branches:
      - "main"

jobs:
  prepration:
    runs-on: ubuntu-latest

    steps:
      - run: "Hello, this is test pipeline"

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to Prod server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
